---
# tasks file for kernel_headers

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags: kernel_headers

- include: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags: kernel_headers

- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  tags: kernel_headers
