---
# tasks file for kernel_headers (Ubuntu specific)

- name: Install kernel headers
  apt: >
    name=linux-headers-{{ ansible_kernel }}
    state=present
    update_cache=yes
    cache_valid_time=3600
  tags: kernel_headers
